name: 'Create PR'
description: 'Run scripts and create PRs'
inputs:
  branch_name:
    description: Name of the branch to be created in the current repo
    required: true
  current_repo_name:
    description: Name of the current repo or repo that causes the trigger event
    required: false
    default: ${{ github.event.repository.name }}
  git_pat:
    description: Github Personal Access Token
    required: true
  s2_tools_path:
    description: The PATH to set to run scripts in tools repo
    required: true
  scripts_list:
    description: A list of scripts that needs to be run in the format "script1 --arg_name1 args1 --arg_name2 arg2 script2 args3"
    required: true
  target_repo_name:
    description: Name of the target repo to create the git branch and PR
    required: true
  target_repo_base:
    description: Name of the target repo branch to use as base for the PR
    default: main
    required: false    

runs:
  using: "composite"
  steps:
    - name: Get current date  
      id: date
      shell: bash
      run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H_%M')"
    
    - name: Create a new branch in ${{ inputs.target_repo_name }}
      working-directory: ./${{ inputs.target_repo_name }}
      shell: bash
      run: git checkout -b ${{ inputs.branch_name }}-$DATETIME
      env:
        DATETIME: ${{ steps.date.outputs.date }}

    - name: Run scripts
      working-directory: ./
      shell: bash
      run: |
        export ${{ inputs.s2_tools_path }}
        echo $PATH
        eval "${{ inputs.scripts_list }}"

    - name: Push the new branch with changes after running scripts
      working-directory: ./${{ inputs.target_repo_name }}
      shell: bash
      run: |
        git add --all
        git commit -m "Github Actions script runner"
        git push -f origin ${{ inputs.branch_name }}-$DATETIME
      env:
        DATETIME: ${{ steps.date.outputs.date }}

    - name: Create a PR in ${{ inputs.target_repo_name }} repo
      working-directory: ./${{ inputs.target_repo_name }}
      shell: bash
      run: |
        echo "${{ inputs.git_pat }}" > token.txt

        gh auth login --with-token < token.txt
        gh pr create \
          --body "Auto PR created from change in ${{ inputs.current_repo_name }} repo" \
          --title "${{ inputs.branch_name }}-$DATETIME" \
          --head "${{ inputs.branch_name }}-$DATETIME" \
          --base "${{ inputs.target_repo_base }}"
      env:
        DATETIME: ${{ steps.date.outputs.date }}
